program Project1;

uses
  System.StartUpCopy,
  FMX.Forms,
  MaykoFichas.View.Principal in 'View\MaykoFichas.View.Principal.pas' {Form3},
  MFichas.Model.Caixa.Interfaces in 'Model\Caixa\MFichas.Model.Caixa.Interfaces.pas',
  MFichas.Model.Caixa in 'Model\Caixa\MFichas.Model.Caixa.pas',
  MFichas.Model.Caixa.State.Aberto in 'Model\Caixa\State\MFichas.Model.Caixa.State.Aberto.pas',
  MFichas.Model.Caixa.State.Factory in 'Model\Caixa\State\MFichas.Model.Caixa.State.Factory.pas',
  MFichas.Model.Caixa.State.Fechado in 'Model\Caixa\State\MFichas.Model.Caixa.State.Fechado.pas',
  MFichas.Model.Caixa.State.Interfaces in 'Model\Caixa\State\MFichas.Model.Caixa.State.Interfaces.pas',
  MFichas.Model.Caixa.Metodos.Abrir in 'Model\Caixa\Metodos\MFichas.Model.Caixa.Metodos.Abrir.pas',
  MFichas.Model.Caixa.Metodos.Factory in 'Model\Caixa\Metodos\MFichas.Model.Caixa.Metodos.Factory.pas',
  MFichas.Model.Caixa.Metodos.Fechar in 'Model\Caixa\Metodos\MFichas.Model.Caixa.Metodos.Fechar.pas',
  MFichas.Model.Caixa.Metodos.Interfaces in 'Model\Caixa\Metodos\MFichas.Model.Caixa.Metodos.Interfaces.pas',
  MFichas.Model.Caixa.Metodos.Sangria in 'Model\Caixa\Metodos\MFichas.Model.Caixa.Metodos.Sangria.pas',
  MFichas.Model.Caixa.Metodos.Suprimento in 'Model\Caixa\Metodos\MFichas.Model.Caixa.Metodos.Suprimento.pas',
  MFichas.Model.Usuario.Interfaces in 'Model\Usuario\MFichas.Model.Usuario.Interfaces.pas',
  MFichas.Model.Usuario in 'Model\Usuario\MFichas.Model.Usuario.pas',
  MFichas.Model.Usuario.TipoDeUsuario.Caixa in 'Model\Usuario\TipoDeUsuario\MFichas.Model.Usuario.TipoDeUsuario.Caixa.pas',
  MFichas.Model.Usuario.TipoDeUsuario.Factory in 'Model\Usuario\TipoDeUsuario\MFichas.Model.Usuario.TipoDeUsuario.Factory.pas',
  MFichas.Model.Usuario.TipoDeUsuario.Fiscal in 'Model\Usuario\TipoDeUsuario\MFichas.Model.Usuario.TipoDeUsuario.Fiscal.pas',
  MFichas.Model.Usuario.TipoDeUsuario.Gerente in 'Model\Usuario\TipoDeUsuario\MFichas.Model.Usuario.TipoDeUsuario.Gerente.pas',
  MFichas.Model.Usuario.TipoDeUsuario.Interfaces in 'Model\Usuario\TipoDeUsuario\MFichas.Model.Usuario.TipoDeUsuario.Interfaces.pas',
  MFichas.Model.Conexao.Factory in 'Model\Conexao\MFichas.Model.Conexao.Factory.pas',
  MFichas.Model.Conexao.Interfaces in 'Model\Conexao\MFichas.Model.Conexao.Interfaces.pas',
  MFichas.Model.Conexao.SQL in 'Model\Conexao\MFichas.Model.Conexao.SQL.pas',
  MFichas.Controller.Types in 'Controller\MFichas.Controller.Types.pas',
  MFichas.Model.Entidade.CAIXA in 'Model\Entidade\MFichas.Model.Entidade.CAIXA.pas',
  MFichas.Model.Entidade.CAIXAOPERACOES in 'Model\Entidade\MFichas.Model.Entidade.CAIXAOPERACOES.pas',
  MFichas.Model.Entidade.GRUPOPRODUTO in 'Model\Entidade\MFichas.Model.Entidade.GRUPOPRODUTO.pas',
  MFichas.Model.Entidade.PRODUTO in 'Model\Entidade\MFichas.Model.Entidade.PRODUTO.pas',
  MFichas.Model.Entidade.USUARIO in 'Model\Entidade\MFichas.Model.Entidade.USUARIO.pas',
  MFichas.Model.Entidade.VENDA in 'Model\Entidade\MFichas.Model.Entidade.VENDA.pas',
  MFichas.Model.Entidade.VENDAITENS in 'Model\Entidade\MFichas.Model.Entidade.VENDAITENS.pas',
  MFichas.Model.Entidade.VENDAPAGAMENTOS in 'Model\Entidade\MFichas.Model.Entidade.VENDAPAGAMENTOS.pas',
  MFichas.Model.Venda.Interfaces in 'Model\Venda\MFichas.Model.Venda.Interfaces.pas',
  MFichas.Model.Venda in 'Model\Venda\MFichas.Model.Venda.pas',
  MFichas.Model.Venda.State.Abrir in 'Model\Venda\State\MFichas.Model.Venda.State.Abrir.pas',
  MFichas.Model.Venda.State.Factory in 'Model\Venda\State\MFichas.Model.Venda.State.Factory.pas',
  MFichas.Model.Venda.State.Finalizar in 'Model\Venda\State\MFichas.Model.Venda.State.Finalizar.pas',
  MFichas.Model.Venda.State.Interfaces in 'Model\Venda\State\MFichas.Model.Venda.State.Interfaces.pas',
  MFichas.Model.Venda.State.Pagar in 'Model\Venda\State\MFichas.Model.Venda.State.Pagar.pas',
  MFichas.Model.Venda.Metodos.Abrir in 'Model\Venda\Metodos\MFichas.Model.Venda.Metodos.Abrir.pas',
  MFichas.Model.Venda.Metodos.Factory in 'Model\Venda\Metodos\MFichas.Model.Venda.Metodos.Factory.pas',
  MFichas.Model.Venda.Metodos.Finalizar in 'Model\Venda\Metodos\MFichas.Model.Venda.Metodos.Finalizar.pas',
  MFichas.Model.Venda.Metodos.Interfaces in 'Model\Venda\Metodos\MFichas.Model.Venda.Metodos.Interfaces.pas',
  MFichas.Model.Venda.Metodos.Pagar in 'Model\Venda\Metodos\MFichas.Model.Venda.Metodos.Pagar.pas',
  MFichas.Model.Item.Interfaces in 'Model\Item\MFichas.Model.Item.Interfaces.pas',
  MFichas.Model.Item.Iterator in 'Model\Item\MFichas.Model.Item.Iterator.pas',
  MFichas.Model.Item in 'Model\Item\MFichas.Model.Item.pas',
  MFichas.Model.Item.Metodos.Cancelar in 'Model\Item\Metodos\MFichas.Model.Item.Metodos.Cancelar.pas',
  MFichas.Model.Item.Metodos.Devolver in 'Model\Item\Metodos\MFichas.Model.Item.Metodos.Devolver.pas',
  MFichas.Model.Item.Metodos.Factory in 'Model\Item\Metodos\MFichas.Model.Item.Metodos.Factory.pas',
  MFichas.Model.Item.Metodos.GravarNoBanco in 'Model\Item\Metodos\MFichas.Model.Item.Metodos.GravarNoBanco.pas',
  MFichas.Model.Item.Metodos.Interfaces in 'Model\Item\Metodos\MFichas.Model.Item.Metodos.Interfaces.pas',
  MFichas.Model.Item.Metodos.Vender in 'Model\Item\Metodos\MFichas.Model.Item.Metodos.Vender.pas',
  MFichas.Model.Pagamento.Interfaces in 'Model\Pagamento\MFichas.Model.Pagamento.Interfaces.pas',
  MFichas.Model.Pagamento in 'Model\Pagamento\MFichas.Model.Pagamento.pas',
  MFichas.Model.Pagamento.Formas.Factory in 'Model\Pagamento\Formas\MFichas.Model.Pagamento.Formas.Factory.pas',
  MFichas.Model.Pagamento.Formas.Interfaces in 'Model\Pagamento\Formas\MFichas.Model.Pagamento.Formas.Interfaces.pas',
  MFichas.Model.Pagamento.Formas.Credito in 'Model\Pagamento\Formas\Credito\MFichas.Model.Pagamento.Formas.Credito.pas',
  MFichas.Model.Pagamento.Formas.Credito.Processar in 'Model\Pagamento\Formas\Credito\MFichas.Model.Pagamento.Formas.Credito.Processar.pas',
  MFichas.Model.Pagamento.Formas.Debito in 'Model\Pagamento\Formas\Debito\MFichas.Model.Pagamento.Formas.Debito.pas',
  MFichas.Model.Pagamento.Formas.Debito.Processar in 'Model\Pagamento\Formas\Debito\MFichas.Model.Pagamento.Formas.Debito.Processar.pas',
  MFichas.Model.Pagamento.Formas.Dinheiro.Estornar in 'Model\Pagamento\Formas\Dinheiro\MFichas.Model.Pagamento.Formas.Dinheiro.Estornar.pas',
  MFichas.Model.Pagamento.Formas.Dinheiro in 'Model\Pagamento\Formas\Dinheiro\MFichas.Model.Pagamento.Formas.Dinheiro.pas',
  MFichas.Model.Pagamento.Formas.Dinheiro.Processar in 'Model\Pagamento\Formas\Dinheiro\MFichas.Model.Pagamento.Formas.Dinheiro.Processar.pas',
  MFichas.Model.GrupoProduto.Interfaces in 'Model\GrupoProduto\MFichas.Model.GrupoProduto.Interfaces.pas',
  MFichas.Model.GrupoProduto in 'Model\GrupoProduto\MFichas.Model.GrupoProduto.pas',
  MFichas.Model.GrupoProduto.Metodos.Cadastrar in 'Model\GrupoProduto\Metodos\Cadastrar\MFichas.Model.GrupoProduto.Metodos.Cadastrar.pas',
  MFichas.Model.GrupoProduto.Metodos.Buscar in 'Model\GrupoProduto\Metodos\Buscar\MFichas.Model.GrupoProduto.Metodos.Buscar.pas',
  MFichas.Model.Produto.Interfaces in 'Model\Produto\MFichas.Model.Produto.Interfaces.pas',
  MFichas.Model.Produto in 'Model\Produto\MFichas.Model.Produto.pas',
  MFichas.Model.Produto.Metodos.Cadastrar in 'Model\Produto\Metodos\Cadastrar\MFichas.Model.Produto.Metodos.Cadastrar.pas',
  MFichas.Model.Produto.Metodos.Buscar in 'Model\Produto\Metodos\Buscar\MFichas.Model.Produto.Metodos.Buscar.pas',
  MFichas.Controller.Usuario.Interfaces in 'Controller\Usuario\MFichas.Controller.Usuario.Interfaces.pas',
  MFichas.Controller.Usuario in 'Controller\Usuario\MFichas.Controller.Usuario.pas',
  MFichas.Controller.Usuario.Operacoes.Interfaces in 'Controller\Usuario\Operacoes\MFichas.Controller.Usuario.Operacoes.Interfaces.pas',
  MFichas.Controller.Usuario.Operacoes.PedirSenha in 'Controller\Usuario\Operacoes\MFichas.Controller.Usuario.Operacoes.PedirSenha.pas',
  MFichas.Controller.Caixa.Interfaces in 'Controller\Caixa\MFichas.Controller.Caixa.Interfaces.pas',
  MFichas.Controller.Caixa in 'Controller\Caixa\MFichas.Controller.Caixa.pas',
  MFichas.Controller.Caixa.Metodos in 'Controller\Caixa\Metodos\MFichas.Controller.Caixa.Metodos.pas',
  MFichas.View.Dialog.AberturaCaixa in 'View\Dialog\MFichas.View.Dialog.AberturaCaixa.pas' {FrameViewAberturaCaixa: TFrame},
  MFichas.View.Dialog.PedirSenha in 'View\Dialog\MFichas.View.Dialog.PedirSenha.pas' {FrameViewPedirSenha: TFrame},
  MFichas.View.Dialog.ConfirmarProduto in 'View\Dialog\MFichas.View.Dialog.ConfirmarProduto.pas' {FrameConfirmacaoProduto: TFrame},
  MFichas.Controller.Venda.Interfaces in 'Controller\Venda\MFichas.Controller.Venda.Interfaces.pas',
  MFichas.Controller.Venda.Metodos.VenderItem in 'Controller\Venda\Metodos\MFichas.Controller.Venda.Metodos.VenderItem.pas',
  MFichas.Controller.Venda.Metodos in 'Controller\Venda\Metodos\MFichas.Controller.Venda.Metodos.pas',
  MFichas.Controller.Venda in 'Controller\Venda\MFichas.Controller.Venda.pas',
  MFichas.Controller.Eventos in 'Controller\MFichas.Controller.Eventos.pas',
  MFichas.Controller.Records in 'Controller\MFichas.Controller.Records.pas',
  MFichas.Controller.Venda.Metodos.CancelarItem in 'Controller\Venda\Metodos\MFichas.Controller.Venda.Metodos.CancelarItem.pas',
  MFichas.Controller.Venda.Metodos.Pagamento in 'Controller\Venda\Metodos\MFichas.Controller.Venda.Metodos.Pagamento.pas',
  MFichas.Controller.Venda.Metodos.DevolverItem in 'Controller\Venda\Metodos\MFichas.Controller.Venda.Metodos.DevolverItem.pas',
  MFichas.View.Cadastros.Produtos in 'View\Cadastros\MFichas.View.Cadastros.Produtos.pas' {CadastroProdutoView},
  MFichas.Model.Produto.Metodos.Editar in 'Model\Produto\Metodos\Editar\MFichas.Model.Produto.Metodos.Editar.pas',
  MFichas.Model.GrupoProduto.Metodos.Editar in 'Model\GrupoProduto\Metodos\Editar\MFichas.Model.GrupoProduto.Metodos.Editar.pas',
  MFichas.View.Cadastros.GrupoProduto in 'View\Cadastros\MFichas.View.Cadastros.GrupoProduto.pas' {CadastroGrupoProdutoView},
  MFichas.View.Cadastros.Usuarios in 'View\Cadastros\MFichas.View.Cadastros.Usuarios.pas' {CadastrosUsuariosView},
  MFichas.Model.Usuario.Funcoes.Cadastrar in 'Model\Usuario\Funcoes\Cadastrar\MFichas.Model.Usuario.Funcoes.Cadastrar.pas',
  MFichas.Model.Usuario.Funcoes.Editar in 'Model\Usuario\Funcoes\Editar\MFichas.Model.Usuario.Funcoes.Editar.pas',
  MFichas.Model.Usuario.Funcoes.Buscar in 'Model\Usuario\Funcoes\Buscar\MFichas.Model.Usuario.Funcoes.Buscar.pas',
  MFichas.Model.Permissoes.Interfaces in 'Model\Permissoes\MFichas.Model.Permissoes.Interfaces.pas',
  MFichas.Model.Entidade.USUARIOPERMISSOES in 'Model\Entidade\MFichas.Model.Entidade.USUARIOPERMISSOES.pas',
  MFichas.Model.Permissoes.Metodos.Lista in 'Model\Permissoes\Metodos\MFichas.Model.Permissoes.Metodos.Lista.pas',
  MFichas.Model.Permissoes in 'Model\Permissoes\MFichas.Model.Permissoes.pas',
  MFichas.View.Configuracoes in 'View\MFichas.View.Configuracoes.pas' {ConfiguracoesView},
  MFichas.Model.Conexao.Bluetooth in 'Model\Conexao\MFichas.Model.Conexao.Bluetooth.pas',
  MFichas.Model.Permissoes.Metodos.Editar in 'Model\Permissoes\Metodos\MFichas.Model.Permissoes.Metodos.Editar.pas',
  MFichas.Controller.Conexao.Interfaces in 'Controller\Conexao\MFichas.Controller.Conexao.Interfaces.pas',
  MFichas.Model.Produto.Metodos.Buscar.Model in 'Model\Produto\Metodos\Buscar\MFichas.Model.Produto.Metodos.Buscar.Model.pas',
  MFichas.Model.Impressao.Interfaces in 'Model\Impressao\MFichas.Model.Impressao.Interfaces.pas',
  MFichas.Model.Impressao.Caixa.Fechamento in 'Model\Impressao\Caixa\Metodos\MFichas.Model.Impressao.Caixa.Fechamento.pas',
  MFichas.Model.Impressao.Constantes in 'Model\Impressao\MFichas.Model.Impressao.Constantes.pas',
  MFichas.Model.Impressao.Caixa in 'Model\Impressao\Caixa\MFichas.Model.Impressao.Caixa.pas',
  MFichas.Model.Impressao in 'Model\Impressao\MFichas.Model.Impressao.pas',
  MFichas.Model.Usuario.Funcoes.Validacao.ValidarUsuarioESenha in 'Model\Usuario\Funcoes\Validao\MFichas.Model.Usuario.Funcoes.Validacao.ValidarUsuarioESenha.pas',
  MFichas.View.Relatorio in 'View\MFichas.View.Relatorio.pas' {RelatorioView},
  MFichas.Model.Entidade.CONFIGURACOES in 'Model\Entidade\MFichas.Model.Entidade.CONFIGURACOES.pas',
  MFichas.Model.Entidade.EMPRESA in 'Model\Entidade\MFichas.Model.Entidade.EMPRESA.pas',
  MFichas.Model.Empresa.Interfaces in 'Model\Empresa\MFichas.Model.Empresa.Interfaces.pas',
  MFichas.Model.Configuracao.Interfaces in 'Model\Configuracao\MFichas.Model.Configuracao.Interfaces.pas',
  MFichas.Model.Empresa.Metodos.Editar.View in 'Model\Empresa\Metodos\Editar\MFichas.Model.Empresa.Metodos.Editar.View.pas',
  MFichas.Model.Empresa.Metodos.Buscar.View in 'Model\Empresa\Metodos\Buscar\MFichas.Model.Empresa.Metodos.Buscar.View.pas',
  MFichas.Model.Empresa.Metodos.Buscar.Model in 'Model\Empresa\Metodos\Buscar\MFichas.Model.Empresa.Metodos.Buscar.Model.pas',
  MFichas.Model.Empresa in 'Model\Empresa\MFichas.Model.Empresa.pas',
  MFichas.Model.Configuracao.Metodos.Buscar.View in 'Model\Configuracao\Metodos\Buscar\MFichas.Model.Configuracao.Metodos.Buscar.View.pas',
  MFichas.Model.Configuracao.Metodos.Buscar.Model in 'Model\Configuracao\Metodos\Buscar\MFichas.Model.Configuracao.Metodos.Buscar.Model.pas',
  MFichas.Model.Configuracao.Metodos.Editar.View in 'Model\Configuracao\Metodos\Editar\MFichas.Model.Configuracao.Metodos.Editar.View.pas',
  MFichas.Model.Configuracao in 'Model\Configuracao\MFichas.Model.Configuracao.pas',
  qdac_fmx_vkhelper__ in 'Controller\qdac_fmx_vkhelper__.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TForm3, Form3);
  Application.Run;
end.
